-- MySQL Script generated by MySQL Workbench
-- Sat Nov  9 13:01:26 2024


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Oficina
-- -----------------------------------------------------
-- Oficina

-- -----------------------------------------------------
-- Schema Oficina
--
-- Oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Oficina` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Oficina` ;

-- -----------------------------------------------------
-- Table `Oficina`.`Oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Oficina` (
  `idOficina` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `Nome de Fantasia` VARCHAR(45) NULL,
  PRIMARY KEY (`idOficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Oficina_idOficina` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Oficina_idOficina`),
  INDEX `fk_Cliente_Oficina_idx` (`Oficina_idOficina` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Oficina`
    FOREIGN KEY (`Oficina_idOficina`)
    REFERENCES `Oficina`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Placa` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`, `Equipe_idEquipe`),
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Veiculo_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Oficina`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `Oficina`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Mecânico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Oficina_idOficina` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecânico`, `Oficina_idOficina`, `Equipe_idEquipe`),
  INDEX `fk_Mecânico_Oficina1_idx` (`Oficina_idOficina` ASC) VISIBLE,
  INDEX `fk_Mecânico_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecânico_Oficina1`
    FOREIGN KEY (`Oficina_idOficina`)
    REFERENCES `Oficina`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecânico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `Oficina`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Serviço` (
  `idServiço` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Tipo de Serviço` VARCHAR(45) NULL,
  `Data do Serviço` VARCHAR(45) NULL,
  `Oficina_idOficina` INT NOT NULL,
  PRIMARY KEY (`idServiço`, `Oficina_idOficina`),
  INDEX `fk_Serviço_Oficina1_idx` (`Oficina_idOficina` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_Oficina1`
    FOREIGN KEY (`Oficina_idOficina`)
    REFERENCES `Oficina`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Itens de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Itens de Serviço` (
  `idItens de Serviço` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  `Numero de Serie` INT NULL,
  PRIMARY KEY (`idItens de Serviço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Serviço/Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Serviço/Itens` (
  `Itens de Serviço_idItens de Serviço` INT NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Itens de Serviço_idItens de Serviço`, `Serviço_idServiço`),
  INDEX `fk_Itens de Serviço_has_Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Itens de Serviço_has_Serviço_Itens de Serviço1_idx` (`Itens de Serviço_idItens de Serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Itens de Serviço_has_Serviço_Itens de Serviço1`
    FOREIGN KEY (`Itens de Serviço_idItens de Serviço`)
    REFERENCES `Oficina`.`Itens de Serviço` (`idItens de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens de Serviço_has_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `Oficina`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Veiculo/Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Veiculo/Serviço` (
  `Veiculo_idVeiculo` INT NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  `Quantidade` INT NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`Veiculo_idVeiculo`, `Serviço_idServiço`),
  INDEX `fk_Veiculo_has_Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Veiculo_has_Serviço_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_has_Serviço_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `Oficina`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_has_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `Oficina`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oficina`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Oficina`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Data de Emissão` DATE NULL,
  `valor` FLOAT NULL,
  `Veiculo/Serviço_Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo/Serviço_Serviço_idServiço` INT NOT NULL,
  `Data Autorização` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Data Conclusão` DATE NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Veiculo/Serviço_Veiculo_idVeiculo`, `Veiculo/Serviço_Serviço_idServiço`),
  INDEX `fk_Ordem de Serviço_Veiculo/Serviço1_idx` (`Veiculo/Serviço_Veiculo_idVeiculo` ASC, `Veiculo/Serviço_Serviço_idServiço` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Veiculo/Serviço1`
    FOREIGN KEY (`Veiculo/Serviço_Veiculo_idVeiculo` , `Veiculo/Serviço_Serviço_idServiço`)
    REFERENCES `Oficina`.`Veiculo/Serviço` (`Veiculo_idVeiculo` , `Serviço_idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
